python cal_tokens.py dgl.txt --model_name CodeLlama
python cal_tokens.py esm.txt --model_name CodeLlama
python cal_tokens.py External-Attention-pytorch.txt --model_name CodeLlama
python cal_tokens.py Grounded-Segment-Anything.txt --model_name CodeLlama
python cal_tokens.py if.txt --model_name CodeLlama
python cal_tokens.py lavis.txt --model_name CodeLlama
python cal_tokens.py learning3d.txt --model_name CodeLlama
python cal_tokens.py muzic.txt --model_name CodeLlama
python cal_tokens.py open_clip.txt --model_name CodeLlama
python cal_tokens.py PyTorch-GAN.txt --model_name CodeLlama
python cal_tokens.py Time-Series-Library.txt --model_name CodeLlama
python cal_tokens.py vid2vid.txt --model_name CodeLlama
python cal_tokens.py bert.txt --model_name CodeLlama
python cal_tokens.py pytorch-image-models.txt --model_name CodeLlama
